### ISSUE TITLE
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by christopherhm0029** [guruyuga/gurunudi#6]
JSONDecodeError                           Traceback (most recent call last)
<ipython-input-3-5a65a06d652e> in <module>
      5 ai = AI()
      6 
----> 7 response = ai.intent("Larry Page was doing his Phd at Stanford University in 1996.")
      8 print(response)

/srv/conda/envs/notebook/lib/python3.6/site-packages/gurunudi/ai.py in intent(self, text, lang)
    102 		"""
    103 
--> 104                 return self.__call_api(constants.API_INTENT,{constants.FIELD_TEXT:text,constants.FIELD_LANG:lang})
    105 
    106 

/srv/conda/envs/notebook/lib/python3.6/site-packages/gurunudi/ai.py in __call_api(self, api, data)
    248                         url = config.API_URL.format(self.version,api)
    249                         response = requests.post(url, json=data, headers=config.HEADERS)
--> 250                         json=response.json()
    251 
    252                         if config.DEBUG:

/srv/conda/envs/notebook/lib/python3.6/site-packages/requests/models.py in json(self, **kwargs)
    895                     # used.
    896                     pass
--> 897         return complexjson.loads(self.text, **kwargs)
    898 
    899     @property

/srv/conda/envs/notebook/lib/python3.6/json/__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    352             parse_int is None and parse_float is None and
    353             parse_constant is None and object_pairs_hook is None and not kw):
--> 354         return _default_decoder.decode(s)
    355     if cls is None:
    356         cls = JSONDecoder

/srv/conda/envs/notebook/lib/python3.6/json/decoder.py in decode(self, s, _w)
    337 
    338         """
--> 339         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    340         end = _w(s, end).end()
    341         if end != len(s):

/srv/conda/envs/notebook/lib/python3.6/json/decoder.py in raw_decode(self, s, idx)
    355             obj, end = self.scan_once(s, idx)
    356         except StopIteration as err:
--> 357             raise JSONDecodeError("Expecting value", s, err.value) from None
    358         return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by VpkPrasanna** [comment]
Even i have got the same error while checking the package!

**Comment by michris** [comment]
I have the same error ??? Using Python 3.6.
Any idea how to fix this ?

import gurunudi
ai = gurunudi.AI()
response = ai.intent("Larry Page was doing his Phd at Stanford University in 1996.")
print(response)

C:\repos\prive\test\gurundi>python intenttest.py
Traceback (most recent call last):
  File "intenttest.py", line 6, in <module>
    response = ai.intent("Larry Page was doing his Phd at Stanford University in 1996.")
  File "C:\Python36\lib\site-packages\gurunudi\ai.py", line 104, in intent
    return self.__call_api(constants.API_INTENT,{constants.FIELD_TEXT:text,constants.FIELD_LANG:lang})
  File "C:\Python36\lib\site-packages\gurunudi\ai.py", line 250, in __call_api
    json=response.json()
  File "C:\Python36\lib\site-packages\requests\models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Scylla2020** [comment]
Yep their server is down as always. Looks like its been abandoned

**Comment by gurudevrao** [comment]
service currently in beta release for internal testing. will be available for public use shortly. Thank you.

**Comment by DEEP2907** [comment]
@gurudevrao 
Hi im also facing the same issue with latest august release when using Intent Extraction and Chatbot, . can you tell me what is the reason for it ?

 ntent = ai.intent("Delhi is in India")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\deepthipriya.b\Workspace\Python3-6\lib\site-packages\gurunudi\ai.py", line 108, in intent
    return self.__call_api(constants.API_INTENT,{constants.FIELD_TEXT:text,constants.FIELD_LANG:lang})
  File "C:\Users\deepthipriya.b\Workspace\Python3-6\lib\site-packages\gurunudi\ai.py", line 254, in __call_api
    json=response.json()
  File "C:\Users\deepthipriya.b\Workspace\Python3-6\lib\site-packages\requests\models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\deepthipriya.b\Workspace\Python3-6\lib\site-packages\simplejson\__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "C:\Users\deepthipriya.b\Workspace\Python3-6\lib\site-packages\simplejson\decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "C:\Users\deepthipriya.b\Workspace\Python3-6\lib\site-packages\simplejson\decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

response = ai.chat("how are you?")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\deepthipriya.b\Workspace\Python3-6\lib\site-packages\gurunudi\ai.py", line 56, in chat
    return self.__call_api(constants.API_CHAT,{constants.FIELD_TEXT:text,constants.FIELD_LANG:lang})
  File "C:\Users\deepthipriya.b\Workspace\Python3-6\lib\site-packages\gurunudi\ai.py", line 254, in __call_api
    json=response.json()
  File "C:\Users\deepthipriya.b\Workspace\Python3-6\lib\site-packages\requests\models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\deepthipriya.b\Workspace\Python3-6\lib\site-packages\simplejson\__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "C:\Users\deepthipriya.b\Workspace\Python3-6\lib\site-packages\simplejson\decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "C:\Users\deepthipriya.b\Workspace\Python3-6\lib\site-packages\simplejson\decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
>>> translation = ai.translate("New Delhi is the capital of India",lang.GERMAN,lang.ENGLISH)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\deepthipriya.b\Workspace\Python3-6\lib\site-packages\gurunudi\ai.py", line 235, in translate
    return self.__call_api(constants.API_TRANSLATE,{constants.FIELD_TEXT:text,constants.FIELD_LANG:src_lang,constants.FIELD_TARGET_LANG:target_lang})
  File "C:\Users\deepthipriya.b\Workspace\Python3-6\lib\site-packages\gurunudi\ai.py", line 254, in __call_api
    json=response.json()
  File "C:\Users\deepthipriya.b\Workspace\Python3-6\lib\site-packages\requests\models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\deepthipriya.b\Workspace\Python3-6\lib\site-packages\simplejson\__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "C:\Users\deepthipriya.b\Workspace\Python3-6\lib\site-packages\simplejson\decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "C:\Users\deepthipriya.b\Workspace\Python3-6\lib\site-packages\simplejson\decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
