### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by benjlang** [guruyuga/gurunudi#8]
Downloaded the library, and used an example program to test. Keep getting this error:

Traceback (most recent call last):
  File "C:/Users/PycharmProjects/jarvis_new/one.py", line 17, in <module>
    response=ai.chat('who wrote anna karenina?')
  File "C:\Users\PycharmProjects\jarvis_new\venv\lib\site-packages\gurunudi\ai.py", line 52, in chat
    return self.__call_api(constants.API_CHAT,{constants.FIELD_TEXT:text,constants.FIELD_LANG:lang})
  File "C:\Users\PycharmProjects\jarvis_new\venv\lib\site-packages\gurunudi\ai.py", line 250, in __call_api
    json=response.json()
  File "C:\Users\PycharmProjects\jarvis_new\venv\lib\site-packages\requests\models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

I have tried re downloading the library, but the issue does not go away.

**Comment by gurudevrao** [comment]
Will be releasing a new version this week. That should fix the above error.
