### ISSUE TITLE
Json request seems empty

### ISSUE THREAD

**Issue by yannAbouJaoude** [guruyuga/gurunudi#9]
**Describe the bug**
Hi, i dont know why my request seems empty. Is the server down or is the problem between my chair and my screen?
I feel sorry to bother you i am not a programmer...

**Here is the code, i took it raw from the example**

from __future__ import division, print_function, absolute_import
from gurunudi import AI,lang
ai = AI()

response=ai.chat('who wrote anna karenina?') #Here is the error
print(response)

response=ai.chat('qui a écrit anna Karenina?',lang.FRENCH)
print(response)

**Here is my error:**

Traceback (most recent call last):
  File "chatbotv8.py", line 15, in <module>
    response=ai.chat('who wrote anna karenina?')
  File "C:\Users\Yann\AppData\Local\Programs\Python\Python38-32\lib\site-packages\gurunudi\ai.py", line 56, in chat
    return self.__call_api(constants.API_CHAT,{constants.FIELD_TEXT:text,constants.FIELD_LANG:lang})
  File "C:\Users\Yann\AppData\Local\Programs\Python\Python38-32\lib\site-packages\gurunudi\ai.py", line 254, in __call_api
    json=response.json()
  File "C:\Users\Yann\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\Yann\AppData\Local\Programs\Python\Python38-32\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Yann\AppData\Local\Programs\Python\Python38-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Yann\AppData\Local\Programs\Python\Python38-32\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by DEEP2907** [comment]
facing the same issue when using ai.inent()

**Comment by Jheel-patel** [comment]
```
---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
<ipython-input-7-42be25090efe> in <module>()
      4 
      5 doc ="Incentives to draw more private-hire drivers have also been scaled back and Grab is looking at other ways to lower their operating cost and maintain or increase their income.SINGAPORE ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Â The promotional codes and incentives that Grab users previously enjoyed have made way for perks on its loyalty programme GrabRewards, said the ride-hailing firm's Singapore country head Lim Kell Jay on Monday (May 7). Speaking to the media on former rival Uber's last day o"
----> 6 ai.title([doc])

5 frames
/usr/lib/python3.6/json/decoder.py in raw_decode(self, s, idx)
    355             obj, end = self.scan_once(s, idx)
    356         except StopIteration as err:
--> 357             raise JSONDecodeError("Expecting value", s, err.value) from None
    358         return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by gurudevrao** [comment]
Please update your installation to the latest version. Contact us to get your Gurunudi API Key under a pay as you go model.
